# Auto Updates if version is not equal to plugin hardcoded value
version: 0.0.4

# Common numeric settings:
#   -1: No limits / Follow server settings
#   0: Disabled
#   1 or above: Fixed amount

Global:
  # Custom Server Mod
  # if you are using Unknown Server Mod, you can manually set the Mod.
  # Leave it blank when you are already using main Branches, otherwise write a most suitable one
  # Spigot / PaperSeries (Paper and Purpur) / Folia
  Mod: ''
  # Language settings
  # it loads language/EXAMPLE.yml
  Language: english
  # Preserved Names
  # Prevent Clash with other configs
  # Not case-sensitive
  PreservedName:
    - config
    - lang
    - permission
    - flag
  # How many Doll can a player create
  # Not affect already created Doll
  MaxDollPerPlayer: 10
  # Adjust server MAX PLAYER according to the amount of Doll
  # Ensure total amount of join-able real players unchanged
  FlexibleServerMaxPlayer: true
  # How many Doll can server hold
  ServerMaxDoll: -1
  # Allow Doll bypass Player Limit
  BypassMaxPlayer: true
  # Follow to GameRule KeepInventory
  # Overlaps other KeepInventory settings
  FollowKeepInventory: true
  # Do Doll drop loots when die
  # FollowKeepInventory has higher priority
  DollKeepInventory: true
  # Allow Doll bypasses Sleeping count
  # It will not disturb the percentage of skipping night
  DollNotCountSleeping: true
  # Allow player set Doll's skin to any players
  # Default skin: Player who spawned the Doll
  # Mojang's default skin will be applied when Offline mode is true
  RestrictSkin: false
  # Apply prefix to Doll, default: 'BOT-'
  # Prevent clash with real players
  # Not recommended Signs/Space/Special/Non-latin Characters
  # All players have name length of at most 16 (Include Prefix)
  # Beware of doll name + prefix that will longer than 16 Characters
  # Do not change frequently
  DollPrefix: 'BOT-'