name: PlayerDoll
version: '${project.version}'
main: me.autobot.playerdoll.PlayerDoll
api-version: '1.20'
commands:
  doll:
    usage: /<command> <Doll> <action>
  dollReload:

  dollHelp:

  dollList:

