# Auto Updates if version is not equal to plugin hardcoded value
version: 18

# Custom Server Mod
# If plugin has detected the Mod wrongly,
# or you are using Unknown Server Mod, you can manually set the Mod.
# Leave it blank when you are already using main Branches, otherwise write a most suitable one
# Spigot / PaperSeries (include Paper/Purpur/...) / Folia

server-mod: ''
# Language file
# it loads language/EXAMPLE.yml
plugin-language: english
check-update: true
update-replace-config: false
config-auto-reload: false
backup-startup: false
backup-shutdown: false
remove-inactive-doll: false
remove-time: 30 #Days
preserved-doll-name:
    - ''
adjustable-max-player: true
server-max-doll: -1

broadcast-doll-death: true
broadcast-doll-join: false
broadcast-doll-disconnect: false

# Will doll joining Trigger PlayerJoinEvent
# It depends on what plugins you installed in the server
#trigger-player-join-event: false

# Add permission to all Dolls
# It could be helpful in some circumstances
doll-permission:
  - ''

Global:
  # Custom Server Mod
  # If plugin has detected the Mod wrongly,
  # or you are using Unknown Server Mod, you can manually set the Mod.
  # Leave it blank when you are already using main Branches, otherwise write a most suitable one
  # Spigot / PaperSeries (include Paper/Purpur/...) / Folia
  Mod: ''
  # Language settings
  # it loads language/EXAMPLE.yml
  Language: english
  # Enable start up checking
  # Check for new Plugin version
  CheckUpdate: true
  # Replace when Update config
  # If true, it will generate a new config and replace old config
  # All configs will go back to default settings
  # If false, it will add new keys into the existing config
  # Keep old settings, but no newer comments and may mess up config order
  # (new added keys will put at the top of file / parent)
  # If you want to check the new version of default config,
  # open Plugin.jar as Zip and find the config file.
  ReplaceConfig: false
  # Auto-Reload system configs when changes detected
  # config / language / flag / permission
  # Check when Server Start/Reload, /dollReload has no effect
  AutoReload: false
  # Do backup for Doll config directory
  Backup:
    StartUp: false
    ShutDown: false
  # Remove doll data (with player-data) when Server startup
  # When Doll not online for certain days
  # Only doll owner spawning Doll will reset counter
  # Data will lose permanently
  Remove:
    InactiveDoll: false
    # in Days
    Time: 30
  # Preserved Names
  # You can Set names that is disallowed
  # Not case-sensitive
  PreservedName:
    - ''
  # Adjust server MAX PLAYER according to the amount of Doll
  # Ensure capacity of real players unchanged
  FlexibleServerMaxPlayer: true
  # How many Online Doll can server hold
  ServerMaxDoll: -1
  # Allow server broadcast message in these events
  DollDeathMessage: true
  DollJoinMessage: false
  DollDisconnectMessage: false