name: PlayerDoll
version: '${project.version}'
main: me.autobot.playerdoll.PlayerDoll
api-version: '1.20'
folia-supported: true
load: POSTWORLD
commands:
  doll:
    usage: /<command> <Doll> <action>
  dollReload:
    description: Reload
  dollHelp:
    description: Show Help
  dollList:
    description: List Dolls
  dollLimit:
    description: List Permission Info
  dollUpgrade:
    description: Perform Upgrade
softdepend:
  - Residence
  - Vault